spring.application.name=booking-service
spring.datasource.url=${BOOKING_DB_URL:jdbc:postgresql://localhost:5431/booking_service}
spring.datasource.username=${BOOKING_DB_USERNAME:postgres}
spring.datasource.password=${BOOKING_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
