{
  "type": "record",
  "name": "PaymentCancelledEvent",
  "namespace": "com.cinema.kafka.event",
  "fields": [
    {
      "name": "payload",
      "type": {
        "type": "record",
        "name": "PaymentCancelledEventPayload",
        "fields": [
          { "name": "paymentId", "type": "string" },
          { "name": "bookingId", "type": "string" },
          { "name": "catalogSessionId", "type": "string" },
          { "name": "catalogSeatIds", "type": { "type": "array", "items": "string" } },
          { "name": "totalPrice", "type": "string" },
          { "name": "currency", "type": "string" },
          { "name": "stripeCheckoutSessionId", "type": "string" },
          { "name": "cancelledAt", "type": "string" },
          { "name": "reason", "type": "string" },
          { "name": "status", "type": "string" }
        ]
      }
    }
  ]
}
