{
  "type": "record",
  "name": "PaymentCompletedEvent",
  "namespace": "com.cinema.kafka.event",
  "fields": [
    {
      "name": "payload",
      "type": {
        "type": "record",
        "name": "PaymentCompletedEventPayload",
        "fields": [
          { "name": "paymentId", "type": "string" },
          { "name": "bookingId", "type": "string" },
          { "name": "totalPrice", "type": "string" },
          { "name": "currency", "type": "string" },
          { "name": "stripeCheckoutSessionId", "type": "string" },
          { "name": "completedAt", "type": "string" },
          { "name": "status", "type": "string" }
        ]
      }
    }
  ]
}
