# SPRING
spring.application.name=payment-service
spring.datasource.url=${PAYMENT_DB_URL:jdbc:postgresql://localhost:5431/payment_service}
spring.datasource.username=${PAYMENT_DB_USERNAME:postgres}
spring.datasource.password=${PAYMENT_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
server.port=8084

# KAFKA & SCHEMA REGISTRY
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVER:localhost:9094}
spring.kafka.properties.schema.registry.url=${SCHEMA_REGISTRY_URL:http://localhost:8081}

# CONSUMER
spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.specific.avro.reader=true

# PRODUCER
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer

# TOPICS
app.kafka.topics.payment-completed=${PAYMENT_COMPLETED_TOPIC:dev.cinema.payment-completed.v1}
app.kafka.topics.payment-cancelled=${PAYMENT_CANCELLED_TOPIC:dev.cinema.payment-cancelled.v1}
app.kafka.topics.refund-started=${REFUND_STARTED_TOPIC:dev.cinema.refund-started.v1}
app.kafka.topics.refund-completed=${REFUND_COMPLETED_TOPIC:dev.cinema.refund-completed.v1}

# OUTBOX POLLING
app.outbox.poll-delay-ms=${OUTBOX_POLL_DELAY_MS:2000}
app.outbox.batch-size=${OUTBOX_BATCH_SIZE:50}

# STRIPE
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
stripe.session-expiration-minutes=${STRIPE_SESSION_EXPIRATION_MINUTES:30}
stripe.success-url=${STRIPE_SUCCESS_URL:http://localhost:8084/api/v1/payments/success?bookingId={BOOKING_ID}}
stripe.cancel-url=${STRIPE_CANCEL_URL:http://localhost:8084/api/v1/payments/cancel?bookingId={BOOKING_ID}}

