# SPRING
spring.application.name=payment-service
spring.datasource.url=${PAYMENT_DB_URL:jdbc:postgresql://localhost:5431/payment_service}
spring.datasource.username=${PAYMENT_DB_USERNAME:postgres}
spring.datasource.password=${PAYMENT_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
server.port=8082

# KAFKA
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVER:localhost:9094}
