create table payment (
    id bigint generated by default as identity primary key,
    stripe_payment_intent_id varchar(255) unique,
    stripe_checkout_session_id varchar(255) not null unique,
    amount bigint not null,
    currency varchar(16) not null,
    current_status varchar(32) not null
);

create table booking (
    id bigint generated by default as identity primary key,
    payment_id bigint not null,
    booking_id bigint not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_payment_booking_payment
        foreign key (payment_id) references payment (id)
);

create index idx_payment_booking_payment_id on booking (payment_id);

create table payment_status_history (
    id bigint generated by default as identity primary key,
    payment_id bigint not null,
    status varchar(32) not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_payment_status_history_payment
        foreign key (payment_id) references payment (id),
    constraint chk_payment_status_history_status
        check (status in ('in_progress', 'completed', 'expired', 'cancelled'))
);

create index idx_payment_status_history_payment_id on payment_status_history (payment_id);

create table refund (
    id bigint generated by default as identity primary key,
    payment_id bigint not null,
    stripe_refund_id varchar(255) not null unique,
    amount bigint not null,
    status varchar(32) not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_refund_payment
        foreign key (payment_id) references payment (id),
    constraint chk_refund_status
        check (status in ('in_progress', 'completed', 'failed'))
);

create index idx_refund_payment_id on refund (payment_id);

create table stripe_webhook_event (
    id bigint generated by default as identity primary key,
    stripe_event_id varchar(255) not null unique,
    created_at timestamp not null default current_timestamp
);