ervices:
  cinema-kafka-1:
    image: apache/kafka:latest
    container_name: cinema-kafka-1
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CLUSTER_ID: 'lQC5smYaRKizbAAADSPeKw'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@cinema-kafka-1:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:9092,
        CONTROLLER://0.0.0.0:9093,
        EXTERNAL://0.0.0.0:9094
      ### UPDATE HOST ###
      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://cinema-kafka-1:9092,
        EXTERNAL://141.144.247.230:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 1
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    volumes:
      - ./kafka_data:/var/lib/kafka/data

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.0
    container_name: cinema-schema-registry
    restart: no
    ports:
      - "8081:8081"
    depends_on:
      cinema-kafka-1:
        condition: service_healthy
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: cinema-kafka-1:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  cinema-kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: cinema-kafka-ui
    ports:
      - "9090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: cinema-kafka-1:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      cinema-kafka-1:
        condition: service_healthy
      schema-registry:
        condition: service_started

volumes:
  kafka_data: