--------------  GET  ------------------
###
# @name getSessions
GET http://{{booking-service}}/api/v1/movie-sessions
Content-Type: application/json

###
# @name getUsers
GET http://{{booking-service}}/api/v1/users
Content-Type: application/json

###
# @name getBookings
GET http://{{booking-service}}/api/v1/bookings?userId=ca11ace7-0343-4774-b459-8a1a8a7c576d
Content-Type: application/json

--------------  POST  ------------------
###
# @name createBooking
POST http://localhost:8082/api/v1/bookings
Content-Type: application/json

{
  "userId": "ca11ace7-0343-4774-b459-8a1a8a7c576d",
  "movieSessionId": "e516aed9-b67d-4427-9478-fd53acc3b2af",
  "seatIds": [
    "a8e3cca2-ae6d-4ac7-9378-57b97d8bc4bc"
  ]
}

###
POST http://localhost:8082/api/v1/bookings/adc68e1a-8b01-43bf-b958-1b4fe2ef09cb/cancel
Content-Type: application/json


