--------------  GET  ------------------
###
# @name getSessions
GET http://{{booking-service}}/api/v1/movie-sessions
Content-Type: application/json

###
# @name getUsers
GET http://{{booking-service}}/api/v1/users
Content-Type: application/json

###
# @name getBookings
GET http://{{booking-service}}/api/v1/bookings?userId={{getUsers.response.body.$[0].id}}
Content-Type: application/json

--------------  POST  ------------------
###
# @name createBooking
POST https://{{booking-service}}/api/v1/bookings
Content-Type: application/json

{
  "userId": "{{getUsers.response.body.$[0].id}}",
  "movieSessionId": "{{getSessions.response.body.$[0].id}}",
  "seatIds": [
    "0823586e-e22e-46fd-8440-35a972032c67"
  ]
}

###
POST https://{{booking-service}}/api/v1/bookings/b4f0751d-7713-49f6-9ca2-08f00dd067f4/cancel
Content-Type: application/json


