--------------  GET  ------------------
###
# @name getAuditoriums
GET http://{{catalog-service}}/api/v1/auditoriums
Content-Type: application/json

###
# @name getMovies
GET http://{{catalog-service}}/api/v1/movies
Content-Type: application/json

###
GET http://{{catalog-service}}/api/v1/sessions
Content-Type: application/json



--------------  POST  ------------------
###
POST http://{{catalog-service}}/api/v1/sessions
Content-Type: application/json

{
  "auditoryId": "{{getAuditoriums.response.body.$[0].id}}",
  "movieId": "{{getMovies.response.body.$[0].id}}",
  "startsAt": "{{$datetime iso8601 1 d}}",
  "endsAt": "{{$datetime iso8601 26 h}}",
  "basePrice": 12.50,
  "status": "SCHEDULED"
}

###
POST http://{{catalog-service}}/api/v1/sessions
Content-Type: application/json

{
  "auditoryId": "{{getAuditoriums.response.body.$[0].id}}",
  "movieId": "{{getMovies.response.body.$[0].id}}",
  "startsAt": "{{$datetime iso8601 1 d}}",
  "endsAt": "{{$datetime iso8601 26 h}}",
  "basePrice": 14.00,
  "status": "SCHEDULED"
}

###
POST http://{{catalog-service}}/api/v1/sessions
Content-Type: application/json

{
  "auditoryId": "{{getAuditoriums.response.body.$[0].id}}",
  "movieId": "{{getMovies.response.body.$[0].id}}",
  "startsAt": "{{$datetime iso8601 1 d}}",
  "endsAt": "{{$datetime iso8601 26 h}}",
  "basePrice": 11.00,
  "status": "SCHEDULED"
}

###
POST http://{{catalog-service}}/api/v1/sessions
Content-Type: application/json

{
  "auditoryId": "{{getAuditoriums.response.body.$[0].id}}",
  "movieId": "{{getMovies.response.body.$[0].id}}",
  "startsAt": "{{$datetime iso8601 1 d}}",
  "endsAt": "{{$datetime iso8601 26 h}}",
  "basePrice": 14.00,
  "status": "SCHEDULED"
}