--------------  GET  ------------------
###
GET http://{{booking-service}}/api/v1/users
Content-Type: application/json



--------------  POST  ------------------
###
POST https://{{booking-service}}/api/v1/users
Content-Type: application/json

{
  "email": "alice@example.com",
  "name": "Alice"
}

###
POST https://{{booking-service}}/api/v1/users
Content-Type: application/json

{
  "email": "bob@example.com",
  "name": "Bob"
}


