name: 'Deploy Booking Service'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'booking-service/**'
      - '.github/workflows/reusable-cd.yml'
      - '.github/workflows/booking-service-cd.yml'

jobs:
  run-shared-cd:
    uses: ./.github/workflows/reusable-cd.yml
    with:
      service-name: 'Booking Service'
      service-path: 'booking-service'
    secrets: inherit