name: 'Deploy Catalog Service'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'catalog-service/**'
      - '.github/workflows/reusable-cd.yml'
      - '.github/workflows/catalog-service-cd.yml'

jobs:
  run-shared-cd:
    uses: ./.github/workflows/reusable-cd.yml
    with:
      service-name: 'Catalog Service'
      service-path: 'catalog-service'
    secrets: inherit