name: 'Deploy Catalog Service'

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'catalog-service/**'
      - '.github/workflows/deploy-catalog.yml'
  push:
    branches:
      - main
    paths:
      - 'catalog-service/**'
      - '.github/workflows/deploy-catalog.yml'


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build ./catalog-service/ -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/cinema-catalog-service:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/cinema-catalog-service:${{ github.sha }}

      - name: Restart ACI to pull new image
        run: |
          az container restart \
            --name cr-cinema-catalog-service-dev-pl-01 \
            --resource-group rg-cinema-dev-pl