name: 'Deploy Payment Service'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'payment-service/**'
      - '.github/workflows/reusable-cd.yml'
      - '.github/workflows/payment-service-cd.yml'

jobs:
  run-shared-cd:
    uses: ./.github/workflows/reusable-cd.yml
    with:
      service-name: 'Payment Service'
      service-path: 'payment-service'
    secrets: inherit